### ISSUE TITLE
Streams().first()

### ISSUE THREAD

**Issue by OLBEA20** [keotl/jivago#63]
**AS** a user of the Stream class of Jivago **I** would like to have a `first()` function to retrieve the first element of a given Stream.

**Acceptance Criteria**

```python
a_list = [1,2,3]

first = Stream(a_list).first()

assertEqual(1, first)
```

```python
an_empty_list = []

first = Stream(an_empty_list).first()

assertIsNone(first)
```

**Note**: A java `Optional` equivalent could be implemented to handle second case.

**Comment by keotl** [comment]
#65 Done
